import streamlit as st
import pandas as pd
import numpy as np
import joblib
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import (
    accuracy_score, roc_auc_score, precision_score,
    recall_score, f1_score, matthews_corrcoef,
    confusion_matrix, classification_report
)

st.set_page_config(page_title="ML Classification Dashboard", layout="wide")

# ── Constants ─────────────────────────────────────────────────────────────────
MODEL_FILES = {
    "Logistic Regression": "model/Logistic_Regression.pkl",
    "Decision Tree":        "model/Decision_Tree.pkl",
    "kNN":                  "model/kNN.pkl",
    "Naive Bayes":          "model/Naive_Bayes.pkl",
    "Random Forest":        "model/Random_Forest.pkl",
}
SCALED_MODELS = {"Logistic Regression", "kNN", "Naive Bayes"}
TARGET_COL = "income"

# ── Helpers ───────────────────────────────────────────────────────────────────
@st.cache_resource
def load_model(path):
    return joblib.load(path)

@st.cache_resource
def load_scaler():
    return joblib.load("model/scaler.pkl")

def compute_metrics(y_true, y_pred, y_prob):
    return {
        "Accuracy":  round(accuracy_score(y_true, y_pred), 4),
        "AUC":       round(roc_auc_score(y_true, y_prob), 4),
        "Precision": round(precision_score(y_true, y_pred), 4),
        "Recall":    round(recall_score(y_true, y_pred), 4),
        "F1":        round(f1_score(y_true, y_pred), 4),
        "MCC":       round(matthews_corrcoef(y_true, y_pred), 4),
    }

def plot_confusion_matrix(y_true, y_pred, model_name):
    cm = confusion_matrix(y_true, y_pred)
    fig, ax = plt.subplots(figsize=(4, 3))
    sns.heatmap(cm, annot=True, fmt="d", cmap="Blues",
                xticklabels=["<=50K", ">50K"],
                yticklabels=["<=50K", ">50K"], ax=ax)
    ax.set_xlabel("Predicted")
    ax.set_ylabel("Actual")
    ax.set_title(f"Confusion Matrix — {model_name}")
    plt.tight_layout()
    return fig

# ── Sidebar ───────────────────────────────────────────────────────────────────
st.sidebar.title("ML Classification Dashboard")
st.sidebar.markdown("**Dataset:** Adult Income (UCI)")
st.sidebar.markdown("**Task:** Binary Classification (Income >50K?)")
st.sidebar.divider()

uploaded_file = st.sidebar.file_uploader(
    "Upload Test Data (CSV)", type=["csv"],
    help="Upload test_data.csv generated by train_models.py"
)

selected_model = st.sidebar.selectbox(
    "Select Model", list(MODEL_FILES.keys())
)

compare_all = st.sidebar.checkbox("Compare All Models", value=False)

# ── Main ──────────────────────────────────────────────────────────────────────
st.title("ML Classification Dashboard")
st.markdown("### Adult Income Dataset — 5 Classifier Comparison")

if uploaded_file is None:
    st.info("Upload `test_data.csv` using the sidebar to get started.")
    st.markdown("""
    **Expected format:** The CSV must contain all feature columns plus an `income` target column.
    Run `python model/train_models.py` first to generate `test_data.csv` and the saved model files.
    """)
    st.stop()

# Load data
df = pd.read_csv(uploaded_file)
if TARGET_COL not in df.columns:
    st.error(f"Target column `{TARGET_COL}` not found in uploaded CSV.")
    st.stop()

X = df.drop(TARGET_COL, axis=1)
y = df[TARGET_COL]

st.markdown(f"**Rows loaded:** {len(df)} &nbsp;&nbsp; **Features:** {X.shape[1]}")

scaler = load_scaler()

# ── Single model view ─────────────────────────────────────────────────────────
if not compare_all:
    st.subheader(f"Results — {selected_model}")

    model = load_model(MODEL_FILES[selected_model])
    X_input = scaler.transform(X) if selected_model in SCALED_MODELS else X.values

    y_pred = model.predict(X_input)
    y_prob = model.predict_proba(X_input)[:, 1]
    metrics = compute_metrics(y, y_pred, y_prob)

    # Metric cards
    cols = st.columns(6)
    for col, (k, v) in zip(cols, metrics.items()):
        col.metric(k, v)

    st.divider()
    col1, col2 = st.columns([1, 1])

    with col1:
        st.subheader("Confusion Matrix")
        fig = plot_confusion_matrix(y, y_pred, selected_model)
        st.pyplot(fig)

    with col2:
        st.subheader("Classification Report")
        report = classification_report(
            y, y_pred, target_names=["<=50K", ">50K"], output_dict=True
        )
        st.dataframe(pd.DataFrame(report).transpose().round(4))

# ── Compare all models ────────────────────────────────────────────────────────
else:
    st.subheader("All Models — Side-by-Side Comparison")

    all_metrics = []
    all_preds = {}

    for name, path in MODEL_FILES.items():
        model = load_model(path)
        X_input = scaler.transform(X) if name in SCALED_MODELS else X.values
        y_pred = model.predict(X_input)
        y_prob = model.predict_proba(X_input)[:, 1]
        m = compute_metrics(y, y_pred, y_prob)
        m["Model"] = name
        all_metrics.append(m)
        all_preds[name] = (y_pred, y_prob)

    results_df = pd.DataFrame(all_metrics).set_index("Model")
    st.dataframe(results_df.style.highlight_max(axis=0, color="#d4edda")
                                  .highlight_min(axis=0, color="#f8d7da"), use_container_width=True)

    st.divider()
    st.subheader("Confusion Matrices")
    cols = st.columns(3)
    for i, (name, (y_pred, _)) in enumerate(all_preds.items()):
        with cols[i % 3]:
            fig = plot_confusion_matrix(y, y_pred, name)
            st.pyplot(fig)

    st.divider()
    st.subheader("Metric Comparison Chart")
    metric_choice = st.selectbox("Metric to visualize", ["Accuracy", "AUC", "F1", "MCC", "Precision", "Recall"])
    fig2, ax2 = plt.subplots(figsize=(8, 4))
    bars = ax2.bar(results_df.index, results_df[metric_choice], color=sns.color_palette("Blues_d", len(results_df)))
    ax2.set_ylabel(metric_choice)
    ax2.set_title(f"{metric_choice} by Model")
    ax2.set_ylim(0, 1)
    for bar, val in zip(bars, results_df[metric_choice]):
        ax2.text(bar.get_x() + bar.get_width() / 2, bar.get_height() + 0.01,
                 f"{val:.4f}", ha="center", va="bottom", fontsize=9)
    plt.xticks(rotation=15)
    plt.tight_layout()
    st.pyplot(fig2)

st.sidebar.divider()
st.sidebar.markdown("M.Tech AIML/DSE — ML Assignment 2")
